# Generated by Django 4.1.1 on 2022-09-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_order", models.IntegerField()),
                ("question_text", models.TextField(max_length=200)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="questionnaire.questionnaire",
                    ),
                ),
            ],
            options={
                "ordering": ["question_order"],
                "unique_together": {("questionnaire", "question_order")},
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_order", models.IntegerField()),
                ("option_text", models.TextField(max_length=200)),
                ("image_resource", models.ImageField(blank=True, upload_to="")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="questionnaire.question",
                    ),
                ),
            ],
            options={
                "ordering": ["option_order"],
                "unique_together": {("question", "option_order")},
            },
        ),
    ]
